In [1]:
import numpy as np

In [2]:
print("hello world")

hello world


In [3]:
arr=np.array([23,65,14,22], np.int8)
print(arr)
print(arr[2])

[23 65 14 22]
14


In [4]:
arr.dtype

dtype('int8')

In [5]:
arr.shape

(4,)

In [6]:
arr.size

4

In [7]:
arr[2]=66
print(arr[2])

66


In [8]:
arr

array([23, 65, 66, 22], dtype=int8)

**zero**

In [9]:
arrzeros=np.zeros(4)

In [10]:
arrzeros

array([0., 0., 0., 0.])

In [11]:
arrzero=np.zeros((3,4))

In [12]:
print(arrzero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**diagonal**

In [13]:
arr_di=np.eye(4)
print(arr_di)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**range**

In [14]:
arr_ran=np.arange(7)
print(arr_ran)

[0 1 2 3 4 5 6]


**linspace**

In [15]:
arr_lin=np.linspace(0,20,num=5)
print(arr_lin)

[ 0.  5. 10. 15. 20.]
