# Random, Data types and Operations

**-----Create numpy arrays with random numbers**

In [1]:
import numpy as np

***rand()***

In [2]:
arr=np.random.rand(3,4)
print(arr)

[[0.49152345 0.50736523 0.81557883 0.04766154]
 [0.79928365 0.63535071 0.27738942 0.53542193]
 [0.88794942 0.52254896 0.70852865 0.31294916]]


***randn()***

In [3]:
arr2=np.random.randn(3,2)
print(arr2)

[[ 0.53191294  0.76395778]
 [-0.26250006  1.63739635]
 [ 0.49287856 -1.12282667]]


***ranf()***

In [4]:
arr3=np.random.ranf(size=(2,2))
print(arr3)

[[0.63882264 0.54129071]
 [0.75822916 0.96120298]]


In [5]:
arr_3=np.random.ranf(3)
print(arr_3)

[0.54752807 0.81724575 0.47059952]


***randint()***

In [6]:
arr4=np.random.randint(2,89,5)
print(arr4)

[ 4 37 45 46 85]


**-----Data types**

In [7]:
var=np.array([1,2,3,4])
print("datatype:-",var.dtype)

datatype:- int64


In [8]:
var2=np.array([23,45,23,11,3], np.int8)
print("datatype:-",var2.dtype)

datatype:- int8


In [9]:
var3=np.array(["a","b","c"])
print("datatype:-",var3.dtype)

datatype:- <U1


In [10]:
var4=np.array(["a",2,"b",45,"c"])
print("datatype:-",var4.dtype)

datatype:- <U21


In [11]:
var5=np.array(([1,2,3,4]), dtype="i")
print(var5.dtype)
print(var5)

int32
[1 2 3 4]


***Max and Min fuctions***

In [12]:
a=np.array([1,2,3,6,33,33,33,4,5,8])
print("maximum value:-",np.max(a),"at",np.argmax(a),"index")
print("minimum value:-",np.min(a),"at",np.argmin(a),"index")

maximum value:- 33 at 4 index
minimum value:- 1 at 0 index


In [13]:
b=np.array([[2,31,43,56],[2,76,35,22]])
print(np.max(b,axis=0))
print(np.max(b,axis=1))

[ 2 76 43 56]
[56 76]


In [14]:
print(np.min(b,axis=0))
print(np.min(b,axis=1))

[ 2 31 35 22]
[2 2]
